"""Auto mode pipeline (TRD §7 mode table): ingress (parallel with rewrite)
→ multi-query hybrid retrieval → sanitizer → rerank → small-to-big →
sufficient-check retry loop → conflict check → generate. On insufficient
evidence after retries the run abstains (TR-4).

Auto always runs this single-hop-with-multi-query-fusion path regardless
of ingress's `complexity` verdict — Plan/Hop/Controller multi-hop lives in
Deep mode (graph/deep.py, TRD §17 row 5), which the user reaches directly
via the mode picker rather than through an Auto complexity branch.
"""

import asyncio
import logging
from collections.abc import AsyncIterator
from dataclasses import dataclass
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from db.models import Chat, Citation, Message
from decisions import DecisionEngine, threshold
from decisions.sanitize import sanitize_chunks
from graph import rewrite as rewrite_node
from graph.abstain import build_abstain_event, stream_abstention
from graph.generate import stream_grounded_answer
from graph.ingress import IngressOutcome, run_ingress
from graph.rewrite import CompleteFn
from graph.timing import EventPublisher, make_step_timer
from providers.llm import complete
from retrieval.cache import get_query_embedding
from retrieval.context import count_tokens, trim_context
from retrieval.expand import ExpandedContext, dedupe_adjacent, expand_context
from retrieval.filters import ClientFilters, Ownership
from retrieval.hybrid import ScoredChunk, hybrid_search
from retrieval.rerank import apply_rerank, get_reranker
from retrieval.web import ensure_web_chunks
from schemas.decisions import Noul
from schemas.events import (
    Abstain,
    Conflict,
    Decision,
    Retrieval,
    RetrievedChunk,
)

logger = logging.getLogger(__name__)

EXCERPT_CHARS = 240
MULTI_QUERY_VARIANTS = 3
MAX_SUFFICIENT_RETRIES = 2
TOP_CHUNKS_FOR_SUFFICIENT = 5


@dataclass(frozen=True)
class AutoRunInput:
    run_id: UUID
    message_id: UUID
    chat_id: UUID
    user_id: UUID
    question: str
    litellm_model: str
    small_model: str
    context_window: int
    source: str
    client_filters: ClientFilters
    collection_ids: list[UUID]


@dataclass
class AutoRun:
    params: AutoRunInput
    history: list[tuple[str, str]]
    contexts: list[ExpandedContext]
    kept_chunks: list[ScoredChunk]
    dropped_chunks: list[ScoredChunk]
    rewritten: str
    retrieval_events: list[Retrieval]
    decision_events: list[Decision]
    conflict_event: Conflict | None
    abstain_event: Abstain | None
    latency_ms: dict[str, int]
    context_used: int
    ingress: IngressOutcome
    sufficiency_p: float = 0.0

    async def stream_answer(self) -> AsyncIterator[str]:
        if self.abstain_event is not None:
            # Abstention path: the fixed-template output is generated by
            # the same streaming generator with a directive prompt — the
            # LLM only renders the template, not free-form text (TR-4).
            async for token in _stream_abstention(self):
                yield token
            return
        async for token in stream_grounded_answer(
            litellm_model=self.params.litellm_model,
            question=self.rewritten,
            contexts=self.contexts,
            history=self.history,
            metadata={
                "run_id": str(self.params.run_id),
                "user_id": str(self.params.user_id),
            },
        ):
            yield token


async def _history(
    session: AsyncSession, chat_id: UUID, exclude_message_id: UUID
) -> list[tuple[str, str]]:
    from sqlalchemy import select

    messages = (
        await session.execute(
            select(Message)
            .where(Message.chat_id == chat_id, Message.id != exclude_message_id)
            .order_by(Message.created_at)
        )
    ).scalars().all()
    return [(m.role, m.content) for m in messages if m.content]


async def _generate_query_variants(
    question: str, small_model: str, complete_fn: CompleteFn, n: int
) -> list[str]:
    """Multi-query rewrite (TRD §7 mode table, Auto only). n variants in
    one LLM call; first variant is the rewritten query itself."""
    if n <= 1:
        return [question]
    from prompts.load import load_prompt

    prompt_template = load_prompt("rewrite.md")
    prompt = prompt_template.format(
        summary="(none — query-variant generation)",
        history="(none)",
        question=question,
    )
    prompt += (
        f"\n\nProduce {n} alternative phrasings of the rewritten question, "
        f"one per line. Each should target a different retrieval angle "
        f"(synonyms, narrower scope, broader scope). No commentary."
    )
    response = await complete_fn(
        litellm_model=small_model,
        messages=[{"role": "system", "content": prompt}, {"role": "user", "content": question}],
        metadata={},
    )
    variants = [question]
    for line in response.strip().splitlines():
        line = line.strip().lstrip("0123456789.-) ")
        if line and line not in variants:
            variants.append(line)
        if len(variants) >= n:
            break
    return variants[:n]


def _fuse_multi_query(result_sets: list[list[ScoredChunk]]) -> list[ScoredChunk]:
    """Reciprocal-rank fusion across query variants."""
    if not result_sets:
        return []
    if len(result_sets) == 1:
        return result_sets[0]
    rrf_k = 60
    fused: dict[UUID, tuple[ScoredChunk, float]] = {}
    for chunks in result_sets:
        for rank, chunk in enumerate(chunks, start=1):
            score = 1.0 / (rrf_k + rank)
            if chunk.chunk_id in fused:
                existing, existing_score = fused[chunk.chunk_id]
                fused[chunk.chunk_id] = (existing, existing_score + score)
            else:
                fused[chunk.chunk_id] = (chunk, score)
    ordered = sorted(fused.values(), key=lambda item: item[1], reverse=True)
    from dataclasses import replace as dc_replace

    return [dc_replace(chunk, fused_score=score) for chunk, score in ordered]


def _sufficient_question(question: str, top_chunks: list[ScoredChunk]) -> Noul:
    evidence = "\n\n".join(
        f"[{i + 1}] {chunk.text[:400]}" for i, chunk in enumerate(top_chunks)
    ) or "(no evidence retrieved)"
    return Noul(
        prompt=(
            "Do the following retrieved chunks together contain enough "
            "evidence to answer the question correctly and completely? "
            "Answer yes only if the answer is fully grounded in the "
            f"evidence.\n\n[question]\n{question}\n\n[evidence]\n{evidence}"
        )
    )


def _conflict_question(top_chunks: list[ScoredChunk]) -> Noul:
    evidence = "\n\n".join(
        f"[{i + 1}] (doc: {chunk.document_name or chunk.source_type}) "
        f"{chunk.text[:400]}"
        for i, chunk in enumerate(top_chunks)
    )
    return Noul(
        prompt=(
            "Do any two of the following chunks disagree about a fact the "
            "question depends on? Yes only if both chunks assert "
            f"incompatible claims.\n\n{evidence}"
        )
    )


async def prepare_auto_run(
    session_factory: async_sessionmaker[AsyncSession],
    params: AutoRunInput,
    engine: DecisionEngine,
    *,
    publish: EventPublisher | None = None,
) -> AutoRun:
    """Run ingress + rewrite + multi-query retrieval + sanitize + rerank +
    sufficient-check retry + conflict check; returns everything the runner
    needs to stream the answer."""

    decision_events: list[Decision] = []
    retrieval_events: list[Retrieval] = []
    latency_ms: dict[str, int] = {}

    _step = make_step_timer(
        node="auto", run_id=params.run_id, latency_ms=latency_ms, publish=publish
    )

    async with session_factory() as session, session.begin():
        chat = await session.get(Chat, params.chat_id)
        history = await _history(session, params.chat_id, params.message_id)
        summary = chat.summary if chat is not None else None
        has_collections = bool(params.collection_ids)

        async def ingress_work() -> IngressOutcome:
            outcome = await run_ingress(
                engine,
                run_id=params.run_id,
                user_message=params.question,
                has_collections=has_collections,
            )
            for name, answer in outcome.answers.items():
                decision_events.append(
                    Decision(
                        run_id=str(params.run_id),
                        name=name,
                        value=answer.value,
                        probability=answer.probability,
                        probabilities=answer.probabilities,
                        engine=answer.engine,
                        latency_ms=answer.latency_ms,
                        reasoning=answer.reasoning,
                    )
                )
            return outcome

        async def rewrite_work() -> str:
            return await rewrite_node.rewrite_query(
                question=params.question,
                history=history,
                summary=summary,
                small_model=params.small_model,
                complete_fn=complete,
            )

        async def ingress_and_rewrite() -> tuple[IngressOutcome, str]:
            ingress_result, rewritten_result = await asyncio.gather(
                ingress_work(), rewrite_work()
            )
            return ingress_result, rewritten_result

        ingress, rewritten = await _step("ingress+rewrite", ingress_and_rewrite)

        if ingress.blocked:
            abstain = Abstain(
                run_id=str(params.run_id),
                found_summary="",
                missing_summary=(
                    "This message was blocked because it appears to attempt "
                    "to manipulate the assistant or extract hidden state."
                ),
                offered_actions=[],
            )
            return AutoRun(
                params=params,
                history=history,
                contexts=[],
                kept_chunks=[],
                dropped_chunks=[],
                rewritten=params.question,
                retrieval_events=[],
                decision_events=decision_events,
                conflict_event=None,
                abstain_event=abstain,
                latency_ms=latency_ms,
                context_used=0,
                ingress=ingress,
            )

        source_filter = params.source
        if params.source == "auto":
            source_filter = ingress.source

        if source_filter in {"web", "both"}:
            await ensure_web_chunks(
                session, query=params.question, chat_id=params.chat_id
            )

        async def retrieval_work() -> tuple[list[ScoredChunk], list[Retrieval]]:
            variants = await _generate_query_variants(
                rewritten, params.small_model, complete, MULTI_QUERY_VARIANTS
            )
            result_sets: list[list[ScoredChunk]] = []
            events: list[Retrieval] = []
            for variant in variants:
                embedding = await get_query_embedding(session, variant)
                ownership = Ownership(
                    user_id=params.user_id,
                    collection_ids=list(params.collection_ids),
                    chat_id=params.chat_id,
                )
                fused = await hybrid_search(
                    session,
                    query_text=variant,
                    query_embedding=embedding,
                    ownership=ownership,
                    filters=params.client_filters,
                    lexical_weight=ingress.lexical_weight,
                )
                result_sets.append(fused)
                events.append(
                    Retrieval(
                        run_id=str(params.run_id),
                        hop=0,
                        query=variant,
                        chunks=[
                            RetrievedChunk(
                                chunk_id=str(c.chunk_id),
                                document_id=str(c.document_id) if c.document_id else None,
                                document_name=c.document_name,
                                page=c.page,
                                heading_path=c.heading_path,
                                source_type=c.source_type,
                                excerpt=c.text[:EXCERPT_CHARS],
                                vector_score=c.vector_score,
                                bm25_score=c.bm25_score,
                                fused_score=c.fused_score,
                                rerank_score=c.rerank_score,
                                dropped=False,
                            )
                            for c in fused
                        ],
                    )
                )
            return _fuse_multi_query(result_sets), events

        fused, retrieval_events = await _step("retrieve", retrieval_work)

        kept, dropped, sanitize_answers = await _step(
            "sanitize",
            lambda: sanitize_chunks(
                engine, run_id=str(params.run_id), chunks=fused
            ),
        )
        for name, answer in sanitize_answers.items():
            decision_events.append(
                Decision(
                    run_id=str(params.run_id),
                    name=name,
                    value=answer.value,
                    probability=answer.probability,
                    probabilities=answer.probabilities,
                    engine=answer.engine,
                    latency_ms=answer.latency_ms,
                    reasoning=answer.reasoning,
                )
            )
        dropped_ids = {c.chunk_id for c in dropped}
        for event in retrieval_events:
            for chunk in event.chunks:
                if chunk.chunk_id in {str(c) for c in dropped_ids}:
                    chunk.dropped = True

        retries_left = MAX_SUFFICIENT_RETRIES
        current_query = rewritten
        while True:
            winners = dedupe_adjacent(
                await apply_rerank(get_reranker(), query=current_query, chunks=kept)
            )
            top_for_check = winners[:TOP_CHUNKS_FOR_SUFFICIENT]
            sufficient_answer = await engine.decide(
                state={"run_id": str(params.run_id), "kind": "sufficient"},
                questions={
                    "sufficient": _sufficient_question(current_query, top_for_check)
                },
            )
            sufficient = sufficient_answer["sufficient"]
            decision_events.append(
                Decision(
                    run_id=str(params.run_id),
                    name="sufficient",
                    value=sufficient.value,
                    probability=sufficient.probability,
                    probabilities=sufficient.probabilities,
                    engine=sufficient.engine,
                    latency_ms=sufficient.latency_ms,
                    reasoning=sufficient.reasoning,
                )
            )
            p_sufficient = float(sufficient.value)
            retry_threshold = threshold("sufficient_retry", sufficient.engine)
            abstain_threshold = threshold("sufficient_abstain", sufficient.engine)
            if p_sufficient >= retry_threshold:
                break
            if p_sufficient < abstain_threshold and retries_left == 0:
                break
            if retries_left > 0:
                retries_left -= 1
                current_query = await rewrite_node.rewrite_query(
                    question=params.question,
                    history=history,
                    summary=summary,
                    small_model=params.small_model,
                    complete_fn=complete,
                )
                embedding = await get_query_embedding(session, current_query)
                ownership = Ownership(
                    user_id=params.user_id,
                    collection_ids=list(params.collection_ids),
                    chat_id=params.chat_id,
                )
                fused_retry = await hybrid_search(
                    session,
                    query_text=current_query,
                    query_embedding=embedding,
                    ownership=ownership,
                    filters=params.client_filters,
                    lexical_weight=ingress.lexical_weight,
                )
                kept_retry, dropped_retry, retry_answers = await sanitize_chunks(
                    engine, run_id=str(params.run_id), chunks=fused_retry
                )
                for name, answer in retry_answers.items():
                    decision_events.append(
                        Decision(
                            run_id=str(params.run_id),
                            name=name,
                            value=answer.value,
                            probability=answer.probability,
                            probabilities=answer.probabilities,
                            engine=answer.engine,
                            latency_ms=answer.latency_ms,
                            reasoning=answer.reasoning,
                        )
                    )
                kept = kept_retry
                dropped = dropped + dropped_retry
                retrieval_events.append(
                    Retrieval(
                        run_id=str(params.run_id),
                        hop=MAX_SUFFICIENT_RETRIES - retries_left,
                        query=current_query,
                        chunks=[
                            RetrievedChunk(
                                chunk_id=str(c.chunk_id),
                                document_id=str(c.document_id) if c.document_id else None,
                                document_name=c.document_name,
                                page=c.page,
                                heading_path=c.heading_path,
                                source_type=c.source_type,
                                excerpt=c.text[:EXCERPT_CHARS],
                                vector_score=c.vector_score,
                                bm25_score=c.bm25_score,
                                fused_score=c.fused_score,
                                rerank_score=c.rerank_score,
                                dropped=c.chunk_id in {d.chunk_id for d in dropped_retry},
                            )
                            for c in fused_retry
                        ],
                    )
                )
                continue
            break

        last_decision = decision_events[-1] if decision_events else None
        p_sufficient_final = (
            float(last_decision.value)
            if last_decision is not None and last_decision.name == "sufficient"
            else 0.0
        )
        abstain_event: Abstain | None = None
        conflict_event: Conflict | None = None
        contexts: list[ExpandedContext] = []

        if p_sufficient_final < threshold("sufficient_abstain", "jev"):
            abstain_event = build_abstain_event(
                str(params.run_id), kept, offered_actions=["web", "deep"]
            )
        else:
            contexts = await expand_context(session, winners)
            conflict_answer_map = await engine.decide(
                state={"run_id": str(params.run_id), "kind": "conflict"},
                questions={"conflict": _conflict_question(winners[:TOP_CHUNKS_FOR_SUFFICIENT])},
            )
            conflict_answer = conflict_answer_map["conflict"]
            decision_events.append(
                Decision(
                    run_id=str(params.run_id),
                    name="conflict",
                    value=conflict_answer.value,
                    probability=conflict_answer.probability,
                    probabilities=conflict_answer.probabilities,
                    engine=conflict_answer.engine,
                    latency_ms=conflict_answer.latency_ms,
                    reasoning=conflict_answer.reasoning,
                )
            )
            if float(conflict_answer.value) >= threshold(
                "conflict_disclose", conflict_answer.engine
            ):
                docs = {c.document_id or c.chunk_id for c in winners[:5]}
                doc_list = list(docs)
                midpoint = max(1, len(doc_list) // 2)
                conflict_event = Conflict(
                    run_id=str(params.run_id),
                    citation_ids_left=[str(d) for d in doc_list[:midpoint]],
                    citation_ids_right=[str(d) for d in doc_list[midpoint:]],
                    rule_applied="user_documents_outrank_web",
                )

        history_tokens = sum(count_tokens(text) for _, text in history[-6:])
        contexts, context_used = trim_context(
            contexts,
            window_tokens=params.context_window,
            history_tokens=history_tokens,
        )

        session.add_all(
            Citation(
                message_id=params.message_id,
                n=i + 1,
                chunk_id=context.chunk.chunk_id,
                rerank_score=context.chunk.rerank_score,
            )
            for i, context in enumerate(contexts)
        )

    return AutoRun(
        params=params,
        history=history,
        contexts=contexts,
        kept_chunks=kept,
        dropped_chunks=dropped,
        rewritten=rewritten,
        retrieval_events=retrieval_events,
        decision_events=decision_events,
        conflict_event=conflict_event,
        abstain_event=abstain_event,
        latency_ms=latency_ms,
        context_used=context_used,
        ingress=ingress,
        sufficiency_p=p_sufficient_final,
    )


async def _stream_abstention(run: AutoRun) -> AsyncIterator[str]:
    if run.abstain_event is None:
        return
    async for token in stream_abstention(run.abstain_event):
        yield token


async def finalize_auto_run(
    session_factory: async_sessionmaker[AsyncSession],
    run: AutoRun,
    *,
    generate_ms: int,
    tokens_in: int,
    tokens_out: int,
) -> None:
    """Post-delivery: refresh the rolling summary if due."""
    async with session_factory() as session, session.begin():
        chat = await session.get(Chat, run.params.chat_id)
        await rewrite_node.maybe_refresh_summary(
            session,
            chat_id=run.params.chat_id,
            summary=chat.summary if chat is not None else None,
            small_model=run.params.small_model,
            complete_fn=complete,
        )
